title: Kim Sunghoon's Blog
description: description
copyright: © Kim Sunghoon

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"